CREATE OR REPLACE STAGE ANALYST
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

COPY FILES
  INTO @ANALYST
  FROM @P_ORCHESTRATION_FRAMEWORK.PUBLIC.GITHUB_P_ORCHESTRATION_FRAMEWORK/branches/main/data/
  PATTERN='.*yaml';

CREATE OR REPLACE STAGE DATA
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

COPY FILES
  INTO @DATA
  FROM @P_ORCHESTRATION_FRAMEWORK.PUBLIC.GITHUB_P_ORCHESTRATION_FRAMEWORK/branches/main/data/
  PATTERN='.*parquet';

CREATE TABLE IF NOT EXISTS SEC_CHUNK_SEARCH (
    RELATIVE_PATH VARCHAR,
    CHUNK VARCHAR
);
CREATE TABLE IF NOT EXISTS SP500 (
    EXCHANGE VARCHAR,
    SYMBOL VARCHAR,
    SHORTNAME VARCHAR,
    LONGNAME VARCHAR,
    SECTOR VARCHAR,
    INDUSTRY VARCHAR,
    CURRENTPRICE NUMBER(38,3),
    MARKETCAP NUMBER(38,0),
    EBITDA NUMBER(38,0),
    REVENUEGROWTH NUMBER(38,3),
    CITY VARCHAR,
    STATE VARCHAR,
    COUNTRY VARCHAR,
    FULLTIMEEMPLOYEES NUMBER(38,0),
    LONGBUSINESSSUMMARY VARCHAR,
    WEIGHT NUMBER(38,20)
);


COPY INTO SEC_CHUNK_SEARCH
FROM @DATA/sec_chunk_search.parquet
FILE_FORMAT = (TYPE = PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO SP500
FROM @DATA/sp500.parquet
FILE_FORMAT = (TYPE = PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


CREATE CORTEX SEARCH SERVICE IF NOT EXISTS SEC_SEARCH_SERVICE
ON CHUNK
attributes RELATIVE_PATH
warehouse='COMPUTE_WH'
target_lag='1d'
AS (
SELECT
    RELATIVE_PATH,
    CHUNK
FROM SEC_CHUNK_SEARCH
);

